### PR TITLE
Added commands to support podman image build and execution.

### PR DESCRIPTION
**Pull request by kachukmarcelo**
Hi, this is my first time contributing to an opensource project. I expect that this pr help with the issue #4

### CODE REVIEW

**Comment by Cereal84** [comment]
Hi @kachukmarcelo,

Thank you for your PR and contribute but the issue #4 was already assigned to @Fabelair. 
Check if there is one issue not assigned yet and comment that you want to work on it.

Before to work on a issue I suggest to you to get the ownership of that issue and comment in the issue asking for more details before start. 
Your code probably work but it should be better have a different behavior, i.e check if docker/podman exists and then run build/run command.

If none of them (docker or podman) exist then return an error message to the user.

**Comment by Cereal84** [comment]
I close this PR.

**Comment by kachukmarcelo** [comment]
Thanks for the comments! Something new to learn... I'll see if I can help with another issue!

**Comment by Cereal84** [comment]
> Thanks for the comments! Something new to learn... I'll see if I can help with another issue!

I'm really sorry.

**Pull request closed without merging**
