### PR TITLE
Add support to Windows

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #3

### CODE REVIEW

**Comment by Cereal84** [comment]
Hi @Brijeshthummar02,
I guess the PR is not completed. The 2 functions for linux and windows installation seems good but as it is right now it didn't work, in fact no one of those 2 functions are called.

We need something like:

```bash

case "$OSTYPE" in
  linux*)     install_linux; exit 1 ;;
  msys*|cygwin*|mingw*)
                  install_windows; exit  1
    ;;  
  *)        echo "unknown: $OSTYPE"; exit 1 ;;
esac
```

**Comment by Cereal84** [comment]
Please rebase your branch and take a look to the install.sh file.
As you can see there is switch case like the one I wrote in the previous comment.

**Comment by Cereal84** [comment]
@Brijeshthummar02 , why did you close the PR ?

**Comment by Cereal84** [comment]
ok you create a new one

**Comment by Brijeshthummar02** [comment]
by mistake i deleted the repo from my system so i've to clone it again and do the change.

**Pull request closed without merging**
