### PR TITLE
Enhance README.md with Conf tab explaination

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #5

### CODE REVIEW

**Comment by Cereal84** [comment]
Hi @Brijeshthummar02 Thank you for your contribute, this PR will be merged in Octorber in order to be counted as valid for Hacktoberfest.

**Comment by Brijeshthummar02** [comment]
Thankyouu for accepting it. i would like to contribute more towards Hacktoberfest issues.

**Comment by Cereal84** [comment]
Thank you for your contribute :)

**Review by Cereal84 — APPROVED** [review]

**Comment by Cereal84** [comment]
Thnk you @Brijeshthummar02  for your work

**Comment by Brijeshthummar02** [comment]
@Cereal84 can you please label hacktoberfest accepted tag to this merge.

**Comment by Cereal84** [comment]
Done

**Pull request merged**
